import Head from 'next/head'
import Defaultlayout from './../layout/Defaultlayout';
import MusicList from './../components/MusicList';

export default function Home() {
  return (
    <>
      <Head>
        <title>myspotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col gap-4'>
        <div className=' text-[24px]'>Discover Soul</div>
        <MusicList/>
      </main>
    </>
  )
}

Home.getLayout = Defaultlayout
